### ISSUE TITLE
Add AUTH option to connection

### ISSUE THREAD

**Issue by Eddie-cz** [mzimbres/aedis#11]
I miss option to assign redis password to connection to properly AUTH.

**Comment by mzimbres** [comment]
You can add AUTH as a normal command in the request, please see https://github.com/mzimbres/aedis/blob/f8ff3034f4250b5b3fa45d713a79dd2274d61a9e/examples/containers.cpp#L33

**Comment by Eddie-cz** [comment]
It seems to negotiate resp3, you need to authenticate with call to HELLO 3...

**Comment by mzimbres** [comment]
Fixed in master, see https://github.com/mzimbres/aedis/blob/6ca0bcc945e306599b9b686971c8c26897e80dda/examples/containers.cpp#L34

**Comment by mzimbres** [comment]
This is fixed in v0.2.0 where sending HELLO 3 is now a user responsibility. If this solves your problem I will close this issue as fixed.

**Comment by Eddie-cz** [comment]
To sum it up: to negotiate protocol, you need to auth first, otherwise it will fall to resp2 with auth after hello.
