### ISSUE TITLE
is_aggregate issue

### ISSUE THREAD

**Issue by Eddie-cz** [mzimbres/aedis#14]
Hello, it's problematic to use custom functions like is_aggregate(type t), which have same name as std counterparts. Simple "using namespace std" in project will make aedis uncompilable. Please rename affected fuction.

Error: aedis/adapter/detail/adapters.hpp(148,11): error : no viable constructor or deduction guide for deduction of template arguments of 'is_aggregate'

**Comment by mzimbres** [comment]
That is no Aedis fault. Fixing the code that pulls `std::is_aggregate` into global namespace is the recommended way of solving this.

**Comment by Eddie-cz** [comment]
While yey, it's taken as bad habit, I still think aedis woulnd't be worse with explixitly namespacing this private library function.
