### ISSUE TITLE
unguarded headers

### ISSUE THREAD

**Issue by Eddie-cz** [mzimbres/aedis#15]
There are still some unguarded headers, like aedis/impl/error.ipp and few others.

**Comment by mzimbres** [comment]
`error.ipp` is an implementation file and not a header. You are probably misusing `#include <aedis/src.hpp>`, it should be include in a single `.cpp` in your application. The easiest way to do this is to include it in the file where you define the `main` function. Alternatively, you can also create a file called `aedis.cpp` with the content

```
#include <aedis/src.hpp>
```
and add it to your build system.

**Comment by Eddie-cz** [comment]
yey, thats is inproper misusing of impl files
