### ISSUE TITLE
fail to reconnect

### ISSUE THREAD

**Issue by wcy168** [mzimbres/aedis#18]
When I run the subscriber example, stopping the redis server for a while and restarting the redis server will cause the program to crash

**Comment by mzimbres** [comment]
I can reproduce the problem, will fix and give feedback soon. Thanks for reporting.

**Comment by mzimbres** [comment]
Fixed on the master. I will add some more tests and make a bugfix release on the weekend.

**Comment by Eddie-cz** [comment]
Just small issue in that example, subscribe is to 'channel', comment points to channel1 (PUBLISH channel1 some-message)
