### ISSUE TITLE
Is this ready?

### ISSUE THREAD

**Issue by WillNilges** [mzimbres/aedis#2]
I'm looking for a solid C++ redis client to use for an embedded project and I stumbled upon this. It looks pretty active, but young. Is this ready for production use?

**Comment by mzimbres** [comment]
I have been using it for over two years now and it is stable. However recently I begin to introduce some breaking changes in the api to support ssl, resp3 and the upcoming C++ asynchronous model that makes it possible to use it with coroutines, callbacks and futures. I am also planning non-allocating buffers and commands. It suits my needs currently.

**Comment by WillNilges** [comment]
Interesting, thanks for the info. Have a star, and I might be back.
