### ISSUE TITLE
fail to compile on linux OS

### ISSUE THREAD

**Issue by wcy168** [mzimbres/aedis#20]
I used aedis::resp3::request in two different header files, and the link failed.The following is the error message

/usr/bin/ld: ./server.o: in function `aedis::adapter::detail::from_bulk(bool&, boost::basic_string_view<char, std::char_traits<char> >, boost::system::error_code&)':
/usr/local/include/aedis/adapter/detail/adapters.hpp:68: multiple definition of `aedis::adapter::detail::from_bulk(bool&, boost::basic_string_view<char, std::char_traits<char> >, boost::system::error_code&)'; ./redis_client.o:/usr/local/include/aedis/adapter/detail/adapters.hpp:68: first defined here
/usr/bin/ld: ./server.o: in function `aedis::adapter::detail::set_on_resp3_error(aedis::resp3::type, boost::system::error_code&)':
/usr/local/include/aedis/adapter/detail/adapters.hpp:93: multiple definition of `aedis::adapter::detail::set_on_resp3_error(aedis::resp3::type, boost::system::error_code&)'; ./redis_client.o:/usr/local/include/aedis/adapter/detail/adapters.hpp:92: first defined here
/usr/bin/ld: ./server.o: in function `aedis::adapt()':
/usr/local/include/aedis/adapt.hpp:141: multiple definition of `aedis::adapt()'; ./redis_client.o:/usr/local/include/aedis/adapt.hpp:141: first defined here
/usr/bin/ld: ./server.o: in function `aedis::adapter::detail::parse_double(char const*, unsigned long, boost::system::error_code&)':
/usr/local/include/aedis/adapter/detail/adapters.hpp:42: multiple definition of `aedis::adapter::detail::parse_double(char const*, unsigned long, boost::system::error_code&)'; ./redis_client.o:/usr/local/include/aedis/adapter/detail/adapters.hpp:42: first defined here
/usr/bin/ld: ./server.o: in function `aedis::adapter::detail::from_bulk(double&, boost::basic_string_view<char, std::char_traits<char> >, boost::system::error_code&)':
/usr/local/include/aedis/adapter/detail/adapters.hpp:75: multiple definition of `aedis::adapter::detail::from_bulk(double&, boost::basic_string_view<char, std::char_traits<char> >, boost::system::error_code&)'; ./redis_client.o:/usr/local/include/aedis/adapter/detail/adapters.hpp:75: first defined here
collect2: 错误：ld 返回 1

**Comment by mzimbres** [comment]
This is probably a misture of src.hpp. Does this comentou help you further https://github.com/mzimbres/aedis/issues/15#issuecomment-1194325177
?

**Comment by wcy168** [comment]
But it can be compiled in windows

**Comment by wcy168** [comment]
Now it works normally. I made a mistake and an obsolete file was introduced into the compilation
