### ISSUE TITLE
example of reconnect

### ISSUE THREAD

**Issue by wcy168** [mzimbres/aedis#21]
Hi, can you provide an example of reconnection using synchronous mode?

**Comment by mzimbres** [comment]
I am working on it right now and will send feedback soon.

**Comment by mzimbres** [comment]
I have implemented automatic reconnection to the `connection` class in the master, for an example on how to use it see https://github.com/mzimbres/aedis/blob/c57f97b8c1d97ee5d23a6cac4c84fe0af1a19b36/examples/subscriber_sync.cpp#L58. Tomorrow I will release v0.3.0, for release notes see https://github.com/mzimbres/aedis/blob/c57f97b8c1d97ee5d23a6cac4c84fe0af1a19b36/CHANGELOG.md#v030.

**Comment by mzimbres** [comment]
I found a bug on reconnecting in the context of events. This weekend I will release a bugfix release. Can we close this ticket?
