### ISSUE TITLE
Port uses std::string type

### ISSUE THREAD

**Issue by wcy168** [mzimbres/aedis#22]
The port number uses the std::string type in config, which is counter intuitive. It is recommended to use the unsigned short type.

**Comment by mzimbres** [comment]
Sorry for the delay, it has been some busy days. Specifying host and port as strings is usually more convenient to the user. This is also what Asio does: https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve/overload3.html

**Comment by wcy168** [comment]
ok
