### ISSUE TITLE
Using  stackless coroutine instead of stateful one.

### ISSUE THREAD

**Issue by enum-class** [mzimbres/aedis#26]
I have found that you use stateful version of coroutine in codes. (async_compose).
Is there any special technical decision about using stackful against stackless coroutines ?

**Comment by mzimbres** [comment]
Hi, I actually use stackless coroutines throughout my code as you can see e.g. [here](https://github.com/mzimbres/aedis/blob/fd82204ba9e6e85b1011c96ebff79539c4227ddf/include/aedis/detail/connection_ops.hpp#L36). As far as I can see `async_compose` is about simplifying the writing of stateful composed operations, that means, it is coroutine agnostic. In other words, you are free to use whatever completion token you like, including stackful coroutines like those provided by asio.
