### ISSUE TITLE
Does aedis support Sentinel?

### ISSUE THREAD

**Issue by portsip** [mzimbres/aedis#4]
Hi, does aedis support Sentinel?

**Comment by mzimbres** [comment]
Hi, it used to support sentinel. After a major refactoring however I
removed it and didn't implement again as I don't need it in my server. Some
commands are also missing.

Marcelo

Em seg., 14 de jun. de 2021 15:55, portsip ***@***.***>
escreveu:

**Comment by mzimbres** [comment]
An example that shows how to use sentinel can be seen in this example [subscriber_sentinel](examples/subscriber_sentinel.cpp).
